name: audio_project
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=0.24.0
  - jupyter
  - ipykernel
  - pytorch>=1.10.0
  - torchvision>=0.11.0
  - torchaudio>=0.10.0
  - cudatoolkit=11.3  # Elimina esta línea si no usarás GPU
  - librosa>=0.8.0
  - pydot>=1.4.2
  - graphviz>=0.16
